[package]
name = "t3-snake-1-T800"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.92"
[dependencies.web-sys]
version = "0.3"
features = ["console"]